export enum ENUM_ESTADO_TURNO {
  ACEPTADO = 'ACEPTADO',
  CANCELADO = 'CANCELADO',
  RECHAZADO = 'RECHAZADO',
  FINALIZADO = 'FINALIZADO',
  PENDIENTE = 'PENDIENTE',
  REALIZADO = 'REALIZADO', // este no se si dejarlo
}
